# Generated by Django 4.2.7 on 2024-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='media_uploading_access',
            field=models.CharField(choices=[('only_owner', 'Only owner'), ('only_owner_and_admins', 'only owner and admins'), ('all', 'All types of users')], default='all', max_length=21, verbose_name='Media Uploading Access Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='writing_access',
            field=models.CharField(choices=[('only_owner', 'Only owner'), ('only_owner_and_admins', 'only owner and admins'), ('all', 'All types of users')], default='all', max_length=21, verbose_name='Writing Access Level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatgroupmember',
            name='access_level',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('admin', 'Admin'), ('owner', 'Owner')], default='normal_user', max_length=11, verbose_name='User Access Level'),
        ),
    ]
